port: 3000
host: "localhost"

auth:
  accessTokenSecret: "secret"
  refreshTokenSecret: "secret"

databases:
  mongodbAccountsUri: "mongodb://mongodb:27017/hawk"
  mongodbEventsUri: "mongodb://mongodb:27017/hawk_events"
