port: 4000
host: "localhost"

metrics:
  enabled: true
  host: localhost
  port: 9090

auth:
  accessTokenSecret: "secret"
  refreshTokenSecret: "secret_refresh"

logging:
  global: info
  metricsServer: error
  appServer: error
  database: info

databases:
  mongodbAccountsUri: "mongodb://mongodb:27017/hawk"
  mongodbEventsUri: "mongodb://mongodb:27017/hawk_events"
