version: "3.2"
services:
  node:
    build:
      dockerfile: "docker/Dockerfile-node"
      context: .
    user: "node"
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    links:
      - mongodb
    ports:
      - 4000:4000
    command: "yarn start"
  mongodb:
    image: mongo
    environment:
      USER: root
      PASS: root
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
