version: "3.4"

services:
  api:
    image: codexteamuser/hawk-api:prod
    network_mode: host
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./.env:/usr/src/app/.env
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - ./tls/ca.pem:${TLS_CA_CERT}
      - ./tls/client.pem:${TLS_CERT}
      - ./tls/client-key.pem:${TLS_KEY}
    restart: unless-stopped
