version: "3.2"
services:
  hawk:
    build:
      dockerfile: "docker/Dockerfile.dev"
      context: .
    user: "node"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=abacaba
      - JWT_SECRET_EVENTS=qwerty
      - PLAYGROUND_ENABLE=true
      - MONGO_HAWK_DB_URL=mongodb://mongodb:27017/hawk
      - MONGO_EVENTS_DB_URL=mongodb://mongodb:27017/hawk_events
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
      - ./docker/mongo-init.js:/scripts/mongo-init.js
    ports:
      - 27017:27017
    command: --bind_ip_all --replSet rs0

volumes:
  mongodata:
