version: "3.2"
services:
  api:
    build:
      dockerfile: "docker/Dockerfile.dev"
      context: .
    user: "node"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./.env:/usr/src/app/.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
