version: "3.2"
services:
  hawk:
    build:
      dockerfile: "docker/Dockerfile.prod"
      context: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
