version: "3.2"
services:
  api-prod:
    build:
      dockerfile: "docker/Dockerfile.prod"
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    volumes:
    - ./.env:/usr/src/app/.env
    - /usr/src/app/node_modules

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
