version: "3.2"
services:
  hawk:
    build:
      dockerfile: "docker/Dockerfile.prod"
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
