version: "3.4"

services:
  api:
    build:
      dockerfile: "docker/Dockerfile.prod"
      context: .
    network_mode: host
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./.env:/usr/src/app/.env
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - ./src/accounting/tls/ca.pem:${TLS_CA_CERT}
      - ./src/accounting/tls/client.pem:${TLS_CERT}
      - ./src/accounting/tls/client-key.pem:${TLS_KEY}
