version: "3.2"
services:
  hawk:
    build:
      dockerfile: "docker/Dockerfile.dev"
      context: .
    user: "node"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=abacaba
      - MONGO_URL=mongodb://mongodb:27017/hawk
      - YANDEX_MAIL_HOST=smtp.yandex.ru
      - YANDEX_MAIL_PORT=465
      - YANDEX_MAIL_USERNAME=
      - YANDEX_MAIL_PASSWORD=
      - YANDEX_SENDER_NAME=
      - YANDEX_SENDER_ADDRESS=
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
