FROM node:12-alpine as builder

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python make musl-dev

COPY package.json yarn.lock ./

RUN yarn install --prod

COPY . .

RUN yarn build

FROM node:12-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/build ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY  ./migrations/ ./migrations/
COPY  ./static/ ./static/
COPY  migrate-mongo-config.js ./
COPY  package.json ./

CMD ["node", "index.js"]
