FROM node:16-alpine as builder

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python3 make musl-dev

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:16-alpine

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python3 make musl-dev

COPY package.json yarn.lock ./

RUN yarn install --prod

COPY --from=builder /usr/src/app/build ./
COPY  ./migrations/ ./migrations/
COPY  ./static/ ./static/
COPY  migrate-mongo-config.js ./

CMD ["node", "index.js"]
