FROM node:16-alpine as builder

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python3 make musl-dev

COPY package.json yarn.lock ./

RUN yarn install

FROM node:16-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY --from=builder /usr/src/app/node_modules ./node_modules

CMD ["yarn", "dev"]
