import { generateText, streamText, type TextStreamPart, type ToolSet } from 'ai';
import { ProviderOptions } from '@ai-sdk/provider-utils';
import type { GuardVerdict, StreamGuard } from '../../services/askAi/security/holdback';

/**
 * Params for a single completion call to the model
 */
export interface CompletionParams {
  /**
   * System instruction that steers the model's behavior
   */
  system: string;

  /**
   * User-facing prompt describing what the model should complete
   */
  prompt: string;
}

/**
 * Params for a streaming completion call to the model
 */
export interface StreamParams extends CompletionParams {
  /**
   * Inspects the model's text before it leaves the server. Supplied by the
   * service layer, because what counts as unsafe output is a domain question,
   * not a transport one. Required: a stream cannot be checked after the fact,
   * so an omitted guard would mean an unchecked answer.
   */
  guard: StreamGuard;

  /**
   * Called once, the first time the guard rejects the answer
   */
  onReject: () => void;
}

/**
 * Wrap the model's stream so every text delta passes through `guard`.
 *
 * Operates on typed stream parts rather than the encoded SSE bytes, where JSON
 * envelopes and escaping would split a marker beyond the reach of any substring
 * scan. The guard's holdback is released on `text-end`, so emitted deltas stay
 * inside the text block they belong to; the TransformStream's own `flush` only
 * covers a stream that ends without one.
 *
 * `stopStream` is not used: it obliges the caller to synthesize finish chunks
 * whose shape follows the SDK version. Suppressing text keeps the stream well
 * formed instead.
 *
 * @param guard - guard for this stream
 * @param onReject - called once when the guard first rejects the answer
 * @returns transform factory accepted by `streamText`
 */
function guardedTransform<TOOLS extends ToolSet>(guard: StreamGuard, onReject: () => void) {
  return (): TransformStream<TextStreamPart<TOOLS>, TextStreamPart<TOOLS>> => {
    let lastTextId: string | null = null;
    let rejectReported = false;

    /**
     * Forward the guard's verdict downstream, reporting a rejection at most once.
     *
     * A rejection travels as an error part rather than more text, so the client
     * can tell it apart from the answer and drop what it has already rendered.
     *
     * @param verdict - what the guard allows to be sent
     * @param controller - transform stream controller
     * @param id - id of the text block the delta belongs to
     */
    const forward = (
      verdict: GuardVerdict,
      controller: TransformStreamDefaultController<TextStreamPart<TOOLS>>,
      id: string | null
    ): void => {
      if (verdict.rejected) {
        if (!rejectReported) {
          rejectReported = true;

          controller.enqueue({
            type: 'error',
            error: new Error(verdict.emit),
          } as TextStreamPart<TOOLS>);

          onReject();
        }

        return;
      }

      if (verdict.emit && id !== null) {
        controller.enqueue({
          type: 'text-delta',
          id,
          text: verdict.emit,
        } as TextStreamPart<TOOLS>);
      }
    };

    return new TransformStream<TextStreamPart<TOOLS>, TextStreamPart<TOOLS>>({
      transform(chunk, controller): void {
        if (chunk.type === 'text-delta') {
          lastTextId = chunk.id;
          forward(guard.push(chunk.text), controller, chunk.id);

          return;
        }

        if (chunk.type === 'text-end') {
          forward(guard.flush(), controller, chunk.id);
        }

        controller.enqueue(chunk);
      },

      flush(controller): void {
        forward(guard.flush(), controller, lastTextId);
      },
    });
  };
}

/**
 * Interface for interacting with Vercel AI Gateway
 *
 * No tools are passed to the model, so a hijacked prompt can only produce text.
 * Adding them requires reworking the security layer first.
 */
class VercelAIApi {
  /**
   * Model ID to use for generating suggestions
   */
  private readonly modelId: string;

  /**
   * Provider Gateway fallback order
   */
  private readonly providerOptions: ProviderOptions;

  /**
   * Set up model id and provider fallback order
   */
  constructor() {
    /**
     * @todo make it dynamic, get from project settings
     */
    this.modelId = 'deepseek/deepseek-v4-flash';
    this.providerOptions = {
      gateway: {
        order: ['novita', 'azure', 'deepseek'],
      },
    };
  }

  /**
   * Send a system/prompt pair to the model and return the generated text
   *
   * @param {CompletionParams} params - system instruction and prompt to complete
   * @returns {Promise<string>} text generated by the model
   */
  public async complete({ system, prompt }: CompletionParams): Promise<string> {
    const { text } = await generateText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
    });

    return text;
  }

  /**
   * Send a system/prompt pair to the model and return the generated text as a stream
   *
   * @param {StreamParams} params - system instruction, prompt and output guard
   * @returns {StreamTextResult} text generated by the model, as a stream
   */
  public stream({ system, prompt, guard, onReject }: StreamParams): ReturnType<typeof streamText> {
    return streamText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
      // eslint-disable-next-line camelcase, @typescript-eslint/camelcase
      experimental_transform: guardedTransform(guard, onReject),
    });
  }
}

export const vercelAIApi = new VercelAIApi();
