import { generateText, streamText } from 'ai';
import { ProviderOptions } from '@ai-sdk/provider-utils';

/**
 * Params for a single completion call to the model
 */
export interface CompletionParams {
  /**
   * System instruction that steers the model's behavior
   */
  system: string;

  /**
   * User-facing prompt describing what the model should complete
   */
  prompt: string;
}

/**
 * Interface for interacting with Vercel AI Gateway
 *
 * No tools are passed to the model, so a hijacked prompt can only produce text.
 * Adding them requires reworking the security layer first.
 */
class VercelAIApi {
  /**
   * Model ID to use for generating suggestions
   */
  private readonly modelId: string;

  /**
   * Provider Gateway fallback order
   */
  private readonly providerOptions: ProviderOptions;

  /**
   * Set up model id and provider fallback order
   */
  constructor() {
    /**
     * @todo make it dynamic, get from project settings
     */
    this.modelId = 'deepseek/deepseek-v4-flash';
    this.providerOptions = {
      gateway: {
        order: ['novita', 'azure', 'deepseek'],
      },
    };
  }

  /**
   * Send a system/prompt pair to the model and return the generated text
   *
   * @param {CompletionParams} params - system instruction and prompt to complete
   * @returns {Promise<string>} text generated by the model
   */
  public async complete({ system, prompt }: CompletionParams): Promise<string> {
    const { text } = await generateText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
    });

    return text;
  }

  /**
   * Send a system/prompt pair to the model and return the generated text as a stream
   *
   * @param {CompletionParams} params - system instruction and prompt to complete
   * @returns {StreamTextResult} text generated by the model, as a stream
   */
  public stream({ system, prompt }: CompletionParams): ReturnType<typeof streamText> {
    return streamText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
    });
  }
}

export const vercelAIApi = new VercelAIApi();
