import { generateText, streamText, type TextStreamPart, type ToolSet } from 'ai';
import { getErrorMessage, ProviderOptions } from '@ai-sdk/provider-utils';
import type { SuggestionStream } from '../../services/askAi/suggestionStream';

/**
 * Params for a single completion call to the model
 */
export interface CompletionParams {
  /**
   * System instruction that steers the model's behavior
   */
  system: string;

  /**
   * User-facing prompt describing what the model should complete
   */
  prompt: string;
}

/**
 * Params for a streaming completion call to the model
 */
export interface StreamParams extends CompletionParams {
  /**
   * Aborted when the answer is no longer wanted, which stops the model
   */
  signal: AbortSignal;
}

/**
 * Translate the SDK's stream parts into suggestion parts, dropping the ones
 * nothing reads.
 *
 * @param parts - stream of parts in the shape the SDK produces
 * @returns {SuggestionStream} the same answer in the domain's terms
 */
async function * toSuggestionStream<TOOLS extends ToolSet>(
  parts: AsyncIterable<TextStreamPart<TOOLS>>
): SuggestionStream {
  for await (const part of parts) {
    if (part.type === 'text-delta') {
      yield {
        type: 'text-delta',
        delta: part.text,
      };
    }

    if (part.type === 'error') {
      yield {
        type: 'error',
        errorText: getErrorMessage(part.error),
      };
    }
  }
}

/**
 * Interface for interacting with Vercel AI Gateway
 *
 * No tools are passed to the model, so a hijacked prompt can only produce text.
 * Adding them requires reworking the security layer first.
 */
class VercelAIApi {
  /**
   * Model ID to use for generating suggestions
   */
  private readonly modelId: string;

  /**
   * Provider Gateway fallback order
   */
  private readonly providerOptions: ProviderOptions;

  /**
   * Set up model id and provider fallback order
   */
  constructor() {
    /**
     * @todo make it dynamic, get from project settings
     */
    this.modelId = 'deepseek/deepseek-v4-flash';
    this.providerOptions = {
      gateway: {
        order: ['novita', 'azure', 'deepseek'],
      },
    };
  }

  /**
   * Send a system/prompt pair to the model and return the generated text
   *
   * @param {CompletionParams} params - system instruction and prompt to complete
   * @returns {Promise<string>} text generated by the model
   */
  public async complete({ system, prompt }: CompletionParams): Promise<string> {
    const { text } = await generateText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
    });

    return text;
  }

  /**
   * Send a system/prompt pair to the model and return the generated text as a stream
   *
   * @param {StreamParams} params - system instruction, prompt and abort signal
   * @returns {SuggestionStream} text generated by the model, as it arrives
   */
  public stream({ system, prompt, signal }: StreamParams): SuggestionStream {
    const { fullStream } = streamText({
      model: this.modelId,
      system,
      prompt,
      providerOptions: this.providerOptions,
      abortSignal: signal,
    });

    return toSuggestionStream(fullStream);
  }
}

export const vercelAIApi = new VercelAIApi();
