name: Build and push docker image

on:
  push:
    branches:
      - prod
      - stage

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/hawk-api
  HAWK_TOKEN: ${{ secrets.HAWK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get package new version name
      - name: Get package info
        id: packageInfo
        uses: codex-team/action-nodejs-package-info@v1

      - name: Send commits to Hawk
        run: |
          curl https://raw.githubusercontent.com/codex-team/hawk.release/feature/commits-sending-script/scripts/commits.sh -O
          chmod +x ./commits.sh
          ./commits.sh -r="${{ steps.package.outputs.version }}" -t=${{ env.HAWK_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          dockerfile: docker/Dockerfile.prod
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}
