name: Bump version in PR

on: [pull_request]

jobs:
  # If pull request was merged then we should check for a package version update
  check-version-update:
    runs-on: ubuntu-22.04
    outputs:
      should-bump: ${{ steps.version-check.outputs.should-bump }}
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Get package new version name
      - name: Get package info
        id: packageNew
        uses: codex-team/action-nodejs-package-info@v1

      # Checkout to the base commit before merge
      - name: Checkout to the base commit before merge
        run: git checkout ${{ github.event.pull_request.base.sha }}

      # Get package old version name
      - name: Get package info
        id: packageOld
        uses: codex-team/action-nodejs-package-info@v1

      # Check if version should be bumped
      - name: Check if version should be bumped
        id: version-check
        run: |
          if [ "${{ steps.packageOld.outputs.version }}" == "${{ steps.packageNew.outputs.version }}" ]; then
            echo "should-bump=true" >> $GITHUB_OUTPUT
          else
            echo "should-bump=false" >> $GITHUB_OUTPUT
          fi

  bump-version:
    needs: check-version-update
    if: needs.check-version-update.outputs.should-bump == 'true'
    runs-on: ubuntu-22.04
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v5

      # Setup node environment
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      # Bump version to the next prerelease (patch) with rc suffix
      - name: Suggest the new version
        run: yarn version --patch --no-git-tag-version

      # Get package new version name
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      # Commit version upgrade
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Bump version up to ${{ steps.package.outputs.version }}"
