name: Run Jest tests on push

on:
  - push

jobs:
  build:
    name: Run Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
      - uses: codecov/codecov-action@v1
